import os
import google.generativeai as genai
from .schemas import FundamentalData, InvestmentMemo, Recommendation
import json
from datetime import datetime

# Initialize Gemini (using API key from environment for now)
# In production, this will be managed via proper secrets/config
# For this script to work, GOOGLE_API_KEY must be set in env

class Brain:
    def __init__(self):
        # We will use the model configured in OpenClaw or env
        # For direct Python usage, we assume the key is available
        if "GOOGLE_API_KEY" in os.environ:
             genai.configure(api_key=os.environ["GOOGLE_API_KEY"])
             self.model = genai.GenerativeModel('gemini-2.5-flash')
        else:
             print("Warning: GOOGLE_API_KEY not found. Brain will run in mock mode if needed.")
             self.model = None

    def generate_memo(self, data: FundamentalData) -> InvestmentMemo:
        if not self.model:
            raise ValueError("Brain not initialized. Missing API Key.")

        prompt = f"""
        You are AlphaGalleon's 'Brain' - an elite, institutional-grade investment analyst.
        
        Analyze the following company data and produce a structured Investment Memo.
        Be direct, critical, and data-driven. Avoid retail fluff.
        
        Company: {data.ticker.name} ({data.ticker.symbol})
        Sector: {data.ticker.sector}
        Price: {data.ticker.current_price}
        Market Cap: {data.ticker.market_cap}
        P/E: {data.ticker.pe_ratio}
        
        Financials:
        - Revenue Growth (3Y): {data.revenue_growth_3y}%
        - Profit Growth (3Y): {data.profit_growth_3y}%
        - Debt/Equity: {data.debt_to_equity}
        - ROE: {data.roe}%
        - Promoter Holding: {data.promoter_holding}%
        
        News Context:
        {data.recent_news_summary}
        
        Output strictly in JSON format matching this schema:
        {{
            "recommendation": "buy" | "sell" | "hold" | "avoid",
            "confidence_score": 0-100,
            "thesis_summary": "...",
            "bull_case": ["point 1", "point 2"],
            "bear_case": ["point 1", "point 2"],
            "catalysts": ["event 1", "event 2"],
            "valuation_verdict": "..."
        }}
        """

        try:
            response = self.model.generate_content(prompt, generation_config={"response_mime_type": "application/json"})
            raw_json = response.text
            parsed = json.loads(raw_json)
            
            return InvestmentMemo(
                ticker_symbol=data.ticker.symbol,
                recommendation=parsed['recommendation'],
                confidence_score=parsed['confidence_score'],
                thesis_summary=parsed['thesis_summary'],
                bull_case=parsed['bull_case'],
                bear_case=parsed['bear_case'],
                catalysts=parsed['catalysts'],
                valuation_verdict=parsed['valuation_verdict'],
                sources=["Generated by AlphaGalleon Brain v1"]
            )
        except Exception as e:
            print(f"Error generating memo: {e}")
            # Fallback/Error handling would go here
            raise e
