import { useQuery } from "convex/react";
import { api } from "../../../convex/_generated/api";
import { formatDistanceToNow } from "date-fns";
import { Clock, Tag, MessageSquare, AlertCircle } from 'lucide-react';

const Memos = () => {
  const memos = useQuery(api.memos.listRecent, { limit: 20 });

  if (!memos) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6 p-6">
      <header>
        <h1 className="text-3xl font-bold text-slate-900">Investment Memos</h1>
        <p className="text-slate-500 mt-2">Latest intelligence generated by The Brain.</p>
      </header>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {memos.map((memo: any) => (
          <div key={memo._id} className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden flex flex-col">
            <div className="p-6">
              <div className="flex justify-between items-start mb-4">
                <div className="flex items-center gap-3">
                  <div className="bg-slate-900 text-white px-3 py-1.5 rounded-lg font-bold text-lg">
                    {memo.symbol}
                  </div>
                  <div className={`px-3 py-1 rounded-lg text-xs font-black uppercase tracking-widest ${
                    memo.verdict === 'BUY' ? 'bg-green-100 text-green-700' :
                    memo.verdict === 'SELL' ? 'bg-red-100 text-red-700' : 'bg-orange-100 text-orange-700'
                  }`}>
                    {memo.verdict}
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mb-1">Confidence</p>
                  <div className="flex items-center gap-2">
                    <div className="w-24 h-2 bg-slate-100 rounded-full overflow-hidden">
                      <div 
                        className={`h-full rounded-full ${
                          memo.confidence > 80 ? 'bg-green-500' : memo.confidence > 50 ? 'bg-orange-500' : 'bg-red-500'
                        }`} 
                        style={{ width: `${memo.confidence}%` }}
                      ></div>
                    </div>
                    <span className="text-sm font-bold text-slate-700">{memo.confidence}%</span>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <div>
                  <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-2 flex items-center gap-1">
                    <MessageSquare size={12} /> Thesis Summary
                  </h4>
                  <p className="text-slate-700 text-sm leading-relaxed italic">
                    "{memo.summary}"
                  </p>
                </div>

                <div>
                  <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-2 flex items-center gap-1">
                    <AlertCircle size={12} /> Reasoning & Data
                  </h4>
                  <div className="bg-slate-50 p-4 rounded-xl text-xs text-slate-600 whitespace-pre-wrap leading-relaxed">
                    {memo.reasoning}
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-auto border-t border-slate-50 bg-slate-50/50 p-4 flex items-center justify-between">
              <div className="flex items-center gap-4 text-xs text-slate-400 font-medium">
                <span className="flex items-center gap-1">
                  <Clock size={14} /> {formatDistanceToNow(memo.generatedAt)} ago
                </span>
                {memo.priceAtGeneration && (
                  <span className="flex items-center gap-1">
                    <Tag size={14} /> Price: ₹{memo.priceAtGeneration.toLocaleString()}
                  </span>
                )}
              </div>
              <button className="text-xs font-bold text-indigo-600 hover:text-indigo-800 transition-colors">
                View Details →
              </button>
            </div>
          </div>
        ))}

        {memos.length === 0 && (
          <div className="col-span-full bg-white rounded-2xl border-2 border-dashed border-slate-200 p-12 text-center">
            <p className="text-slate-400 font-medium">The Brain hasn't generated any memos yet.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default Memos;
